### PR TITLE
Sum, max, min null value fix on non numeric column

### PR DESCRIPTION
**Pull request by gangadhargo**
Hi @mathiasrw 

I tried to fix the following issues please verify and suggest if any changes are required.

https://github.com/AlaSQL/alasql/issues/1533
https://github.com/AlaSQL/alasql/issues/1532
https://github.com/AlaSQL/alasql/issues/1531

### CODE REVIEW

**Comment by mathiasrw** [comment]
Thank you!

**Comment by mathiasrw** [comment]
I added a few more details to the test. Unfortunately its not unfolding as expected.

**Comment by gangadhargo** [comment]
Thanks, sure I am reverifying.

**Comment by gangadhargo** [comment]
Hi @mathiasrw - Sorry, I need some help understanding the code. as i am new to the code base.  I tried debugging and the below **query.groupfn** gives output.
In **dojoin.js** 
**query.groupfn(scope, query.params, alasql);**
how is the above line resolving the output? where is the actual code which compares the input and gives the result? I want to keep validation there. And keeping validations after output doesn't make sense which I did in my initial commit. 

let's say we are doing SUM where is the given input values of sum happening in the code.

**Comment by gangadhargo** [comment]
Hi @mathiasrw, 

I am able to figure out the code and fix the issue. Please ignore the above comment

Thanks,
Gangadhar.

**Comment by mathiasrw** [comment]
@gangadhargo So happy to hear that. Sorry that my response time has been so long.

**Comment by gangadhargo** [comment]
@mathiasrw No worries. I have almost fixed it. only one regression test failed. I am debugging it.

**Comment by mathiasrw** [comment]
Very impressive

**Comment by mathiasrw** [comment]
Released as part of v2.2.0

**Comment by unpete** [comment]
`alasql('select sum(v) from ?', [[{v: 0}]])` returns `[{v: null}]` expected `[{v: 0}]`

**Comment by mathiasrw** [comment]
@unpete Thank you for this input! 

Its very critical. 

@gangadhargo Are you able to take a look at this right away? If not I might need to roll the change back and release again. This will break lots of things. 

Ill add this to the test in your branch

**Comment by mathiasrw** [comment]
I made a PR to your branch @gangadhargo https://github.com/gangadhargo/alasql/pull/1 pull it in, and make a new PR to develop for this

**Comment by mathiasrw** [comment]
Reverting. This has created breaking changes. Lest work together in https://github.com/AlaSQL/alasql/issues/1553 to solve this.

**Comment by gangadhargo** [comment]
sorry guys it was missed. Thanks, @unpete for pointing out this case.  @mathiasrw I will work on this

**Comment by mathiasrw** [comment]
Thank you @gangadhargo 

Please start by merging https://github.com/gangadhargo/alasql/pull/1 into your repo - and then make a new PR to this branch from yours refering to fixing #1553

**Pull request merged**
